import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import sassPlugin from "esbuild-plugin-sass";
import workerPlugin from "@chialab/esbuild-plugin-worker";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	loader: {
		'.ttf': 'copy',
	},
	entryPoints: ["./src/main.ts", "./src/worker.ts", "./src/fonts/IthkuilBasic.ttf", "./src/fonts/IthkuilFlow.ttf", ],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: "./builds/latest",
	minify: prod,
	plugins: [
		sassPlugin(),
		workerPlugin(),
	]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
